#!/bin/bash
#

# push manifest
if [[ ! -d $HOME/.docker ]]
then
    mkdir $HOME/.docker
fi

set -ex

: ${DOCKER_USERNAME:="panta"}

sed -i '/experimental/d' $HOME/.docker/config.json
sed -i '1a"experimental": "enabled",' $HOME/.docker/config.json
docker manifest create ${DOCKER_USERNAME}/gohttpserver \
  ${DOCKER_USERNAME}/gohttpserver:latest \
  ${DOCKER_USERNAME}/gohttpserver:armhf
docker manifest annotate ${DOCKER_USERNAME}/gohttpserver \
  ${DOCKER_USERNAME}/gohttpserver:latest --os linux --arch amd64
docker manifest annotate ${DOCKER_USERNAME}/gohttpserver \
  ${DOCKER_USERNAME}/gohttpserver:armhf --os linux --arch arm --variant v7
docker manifest push ${DOCKER_USERNAME}/gohttpserver

# check again
docker run mplatform/mquery ${DOCKER_USERNAME}/gohttpserver
